//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "menu")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub menu_id: String,
    pub restaurant_id: String,
    pub name: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub image: Vec<u8>,
    pub description: String,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    pub available_quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::restaurant::Entity",
        from = "Column::RestaurantId",
        to = "super::restaurant::Column::RestaurantId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Restaurant,
}

impl Related<super::restaurant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Restaurant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
