//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub mod prelude;

pub mod chat;
pub mod lost_and_found_item;
pub mod maintenance;
pub mod menu;
pub mod message;
pub mod notification;
pub mod order;
pub mod post;
pub mod proposal;
pub mod queue;
pub mod report;
pub mod restaurant;
pub mod ride;
pub mod souvenir;
pub mod store;
pub mod user;
