//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::chat::Entity as Chat;
pub use super::lost_and_found_item::Entity as LostAndFoundItem;
pub use super::maintenance::Entity as Maintenance;
pub use super::menu::Entity as Menu;
pub use super::message::Entity as Message;
pub use super::notification::Entity as Notification;
pub use super::order::Entity as Order;
pub use super::post::Entity as Post;
pub use super::proposal::Entity as Proposal;
pub use super::queue::Entity as Queue;
pub use super::report::Entity as Report;
pub use super::restaurant::Entity as Restaurant;
pub use super::ride::Entity as Ride;
pub use super::souvenir::Entity as Souvenir;
pub use super::store::Entity as Store;
pub use super::transaction::Entity as Transaction;
pub use super::user::Entity as User;
