//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "restaurant")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub restaurant_id: String,
    pub name: String,
    pub description: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub image: Vec<u8>,
    pub location: String,
    pub cuisine_type: String,
    pub operational_status: String,
    pub operational_start_hours: String,
    pub operational_end_hours: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::menu::Entity")]
    Menu,
    #[sea_orm(has_many = "super::user::Entity")]
    User,
}

impl Related<super::menu::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Menu.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
