//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "souvenir")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub souvenir_id: String,
    pub store_id: String,
    pub name: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub image: Vec<u8>,
    pub description: String,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    pub stock: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::store::Entity",
        from = "Column::StoreId",
        to = "super::store::Column::StoreId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Store,
}

impl Related<super::store::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
